### ISSUE TITLE
Implement Video Upload to Youtube Feature

### ISSUE THREAD

**Issue by shantanutheone** [shantanutheone/youtube-as-data-store#1]
Implement following function with defined params
```python
def upload_to_youtube(video_file, name, api_key):
    pass
```

**Comment by Wolfmyths** [comment]
It seems like if we want to use YouTube API this library is required for the project
https://github.com/googleapis/google-api-python-client

Here is some documentation, with code examples under the "Common use cases" header
https://developers.google.com/youtube/v3/docs/videos/insert

**Comment by shantanutheone** [comment]
Yeah, first link is helpful. Just need to figure out if it supports authorization from `api_key` and does not take user to a page for authentication. Also, if it works well with resumable retries, because size of video will be around 50-100x the size of actual file.
